swagger: "2.0"
info:
  title: my-api
  version: 1.0.0

paths:
  /serviceA/hello:
    options:
      summary: CORS preflight
      operationId: optionsServiceA
      responses:
        204:
          description: No content
      security: []
    get:
      summary: Invoke Service A
      operationId: getServiceA
      security:
        - firebase: []
      x-google-backend:
        address: https://service-a-650031894545.us-central1.run.app
      responses:
        200:
          description: OK

  /serviceB/info:
    options:
      summary: CORS preflight
      operationId: optionsServiceB
      responses:
        204:
          description: No content
      security: []
    get:
      summary: Invoke Service B
      operationId: getServiceB
      security:
        - firebase: []
      x-google-backend:
        address: https://service-b-650031894545.us-central1.run.app
      responses:
        200:
          description: OK

securityDefinitions:
  firebase:
    type: oauth2
    flow: implicit
    authorizationUrl: ""
    x-google-issuer: "https://securetoken.google.com/test-apigateway-546c8"
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "test-apigateway-546c8"

x-google-endpoints:
  - name: my-gateway-8amc7fv5.uc.gateway.dev
    allowCors: true
